service: fastapi-serverless
app: example
org: pyropy

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    dockerizePip: non-linux

package:
  exclude:
    - tests/
    - README.md
    - .gitignore
    - venv/
    - node_modules/
  include:
    - app/
    - requirements.txt
    - package.json
    - package-lock.json

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.main.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'