AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fastapi-serverless


Globals:
  Function:
    Timeout: 3

Resources:

  FastAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      OpenApiVersion: '3.0.0'

  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.main.handler
      Runtime: python3.8
      Events:
        MainHandler:
          Type: Api
          Properties:
            RestApiId:
              Ref: FastAPIGateway
            Path: "/{proxy+}"
            Method: ANY

Outputs:
  FastAPIGateway:
    Description: "API Gateway endpoint URL for Prod stage for FastAPI example function"
    Value: !Sub FastAPIGateway.Arn
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn
  FAstAPIFunctionIamRole:
    Description: "Implicit IAM Role created for FastAPI function"
    Value: !GetAtt FastAPIFunctionRole.Arn
