AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fastapi-serverless


Globals:
  Function:
    Timeout: 3

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.main.handler
      Runtime: python3.8
      Events:
        MainHandler:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY

Outputs:
  FastAPI:
    Description: "API Gateway endpoint URL for Prod stage for FastAPI example function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn
  FAstAPIFunctionIamRole:
    Description: "Implicit IAM Role created for FastAPI function"
    Value: !GetAtt FastAPIFunctionRole.Arn
